# tmux configuration file

# set 256 colors
# set -g default-terminal "screen-256color"
# set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'

# bindings 
unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z 

set -g @tpm_plugins_get_path '~/.config/tmux/plugins/'

# Force resurrect to use the path where it actually lives
set -g @resurrect-save-script-path '~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh'
set -g @resurrect-restore-script-path '~/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh'

# Keep your session data on the local SSD
set -g @resurrect-dir '~/.tmux/resurrect'

# --- 2. THE PLUGINS ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# --- 3. PLUGIN CONFIG ---
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# toggle mouse
bind-key M set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

# Mouse scrolling
set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle 
bind-key -T copy-mode-vi y send-keys -X copy-selection

# bind -T root WheelUpPane   if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
# bind -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"

# copy to clipboard
set -as terminal-features ',xterm-256color:clipboard'

# vim style keys
set -g status-keys vi

set -g escape-time 0

# mouse scrolling like emulator
set -g @emulate-scroll-for-no-mouse-alternate-buffer "on"

# window numbering
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind c new-window -c '#{pane_current_path}'
set -g history-limit 50000
set -g focus-events on

# initialize TMUX plugin manager
run '/usr/share/tmux-plugin-manager/tpm'
source-file ~/.config/tmux/zenblue.tmux
